---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-2254-sample-byon-imagestream
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/rhoai-migration-automation.git
    targetRevision: main
    path: rhoai-2254-install/30-samples/byon-imagestream
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-applications
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 60
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 2m
