---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-2254-sample-kfto
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rh-aiservices-bu/rhoai-2.25-baseline.git
    targetRevision: main
    path: rhoai-2254-install/30-samples/kfto
  destination:
    server: https://kubernetes.default.svc
    namespace: pytorch-training
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
