---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-2254-sample-kserve-raw
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: ${TARGET_REVISION}
    path: rhoai-2254-install/30-samples/kserve-raw
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-project-raw
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
